// FILE: src/utils/generateLeukoReportPdf.js  (full rewrite — bordered table, suggestion, signature image only + underline, no "Signature" label)
import { jsPDF } from 'jspdf';
import logo from '../assets/logo.jpeg';
import signature from '../assets/signature.png';
import { loadImageAsDataUrl } from './imageDataUrl';
import { RESULT_META } from './leukemiaClassifier';

async function safeLoad(src) {
  try {
    return await loadImageAsDataUrl(src);
  } catch {
    return null;
  }
}

const SUGGESTIONS = {
  normal: 'No specific action is required. Continue routine annual health checkups and maintain a balanced lifestyle.',
  A: 'Referral to a hematologist is recommended. Please schedule a clinical evaluation as soon as possible.',
  B: 'A hematologist consultation is advised to confirm these findings with laboratory-grade diagnostics.',
  C: 'Maintain a balanced diet, adequate hydration, sufficient rest, and periodic health checkups. A physician consultation is optional.',
  indeterminate: 'These results do not clearly match a single screening category. Please have them reviewed by a qualified physician.'
};

function drawTableRow(doc, y, cols, widths, startX, bold = false) {
  doc.setFont(undefined, bold ? 'bold' : 'normal');
  let x = startX;
  cols.forEach((text, i) => {
    doc.text(String(text), x + 2, y);
    x += widths[i];
  });
  doc.setFont(undefined, 'normal');
}

export async function generateLeukoReportPdf(classification) {
  const { riskClass, table, reasons } = classification;
  const meta = RESULT_META[riskClass];
  const doc = new jsPDF();

  const logoDataUrl = await safeLoad(logo);
  const signatureDataUrl = await safeLoad(signature);

  doc.setFillColor(15, 42, 82);
  doc.rect(0, 0, 210, 32, 'F');
  if (logoDataUrl) doc.addImage(logoDataUrl, 'JPEG', 14, 5, 22, 22);
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.text('Research Academy Bangladesh', 42, 14);
  doc.setFontSize(10);
  doc.text('LeukoScanner — CBC-Based Leukemia Screening Report', 42, 21);
  doc.text(`Generated: ${new Date().toLocaleString('en-GB')}`, 42, 27);

  if (logoDataUrl) {
    doc.saveGraphicsState();
    doc.setGState(new doc.GState({ opacity: 0.06 }));
    doc.addImage(logoDataUrl, 'JPEG', 45, 100, 120, 120);
    doc.restoreGraphicsState();
  }

  let y = 45;
  doc.setTextColor(15, 42, 82);
  doc.setFontSize(14);
  doc.text('CBC Screening Results', 14, y);
  y += 8;

  const startX = 14;
  const colWidths = [50, 40, 50, 42];
  const tableWidth = colWidths.reduce((a, b) => a + b, 0);
  const headerHeight = 8;
  const rowHeight = 8;

  doc.setFillColor(241, 245, 249);
  doc.rect(startX, y, tableWidth, headerHeight, 'F');
  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.2);
  doc.rect(startX, y, tableWidth, headerHeight);
  doc.setFontSize(9.5);
  doc.setTextColor(15, 42, 82);
  drawTableRow(doc, y + 5.5, ['Parameter', 'Your Value', 'Normal Range', 'Status'], colWidths, startX, true);
  y += headerHeight;

  doc.setFontSize(9.5);
  table.forEach((row) => {
    doc.setDrawColor(220, 220, 220);
    doc.rect(startX, y, tableWidth, rowHeight);
    doc.setTextColor(51, 65, 85);
    drawTableRow(doc, y + 5.5, [row.parameter, row.value, row.normalRange, ''], colWidths, startX);
    const isAbnormal = row.status !== 'Normal';
    doc.setTextColor(...(isAbnormal ? [220, 38, 38] : [15, 42, 82]));
    doc.text(row.status, startX + colWidths[0] + colWidths[1] + colWidths[2] + 2, y + 5.5);
    y += rowHeight;
  });
  y += 10;

  doc.setFontSize(13);
  doc.setTextColor(...(riskClass === 'A' ? [220, 38, 38] : [15, 42, 82]));
  doc.text(`Result: ${meta.riskLevel} Risk (${meta.label})`, 14, y);
  y += 8;

  doc.setFontSize(9.5);
  doc.setTextColor(51, 65, 85);
  doc.text('Why this result:', 14, y);
  y += 6;
  reasons.forEach((r) => {
    const lines = doc.splitTextToSize(`• ${r}`, 180);
    doc.text(lines, 16, y);
    y += lines.length * 5;
  });
  y += 6;

  doc.setFontSize(12);
  doc.setTextColor(15, 42, 82);
  doc.text('Suggestion', 14, y);
  y += 7;
  doc.setFontSize(9.5);
  doc.setTextColor(51, 65, 85);
  const suggestionLines = doc.splitTextToSize(SUGGESTIONS[riskClass], 180);
  doc.text(suggestionLines, 14, y);
  y += suggestionLines.length * 5 + 8;

  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  const disclaimer = doc.splitTextToSize(
    'This report is generated by an automated screening tool for informational purposes only and does not constitute a medical diagnosis. Please consult a qualified physician for clinical evaluation.',
    180
  );
  doc.text(disclaimer, 14, y);
  y += disclaimer.length * 4.5 + 10;

  if (y > 240) { doc.addPage(); y = 20; }

  doc.setDrawColor(242, 169, 59);
  doc.setLineWidth(0.8);
  doc.line(14, y, 196, y);
  y += 10;

  doc.setFontSize(11);
  doc.setTextColor(15, 42, 82);
  doc.text('Dr. Momena Begum, MD', 14, y); y += 6;
  doc.setFontSize(9);
  doc.setTextColor(51, 65, 85);
  doc.text('Founder & Academic Director, Research Academy Bangladesh', 14, y); y += 5;
  doc.text('info@researchacademybd.com  |  +880 1234 567890', 14, y);

  const sigX = 140;
  let sigY = y - 25;
  if (signatureDataUrl) {
    doc.addImage(signatureDataUrl, 'PNG', sigX, sigY, 50, 18);
    sigY += 20;
  } else {
    sigY += 20;
  }
  doc.setDrawColor(51, 65, 85);
  doc.setLineWidth(0.3);
  doc.line(sigX, sigY, sigX + 50, sigY);

  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text('© ' + new Date().getFullYear() + ' Research Academy Bangladesh. All rights reserved.', 14, 289);

  doc.save(`leukoscanner-report-${Date.now()}.pdf`);
}